- hosts: localhost
  tasks:
  - name: install git
    yum: name=git state=latest
    become: yes
    become_method: sudo
  - name: clone module
    git:
      repo: https://github.com/shlomilevy10/devops.git
      dest: devops/p1
      clone: yes
  - name: clone spring
    git:
      repo: https://github.com/shlomilevy10/spring-petclinic.git
      dest: devops/spring-petclinic    
      clone: yes
  - name: install docker
    yum: name=docker state=latest
    become: yes
    become_method: sudo
  - name: add "docker" group to "ec2-user"
    user:
      name: ec2-user
      group: docker
      append: yes
    become: yes
    become_method: sudo
  - name: run docker service
    service: 
      name: docker
      state: started
    become: yes
    become_method: sudo





